<a href="https://colab.research.google.com/github/Sumitha-Git/Capstone-Project/blob/main/Numpy_and_Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a 1D NumPy Array:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#Inspect the shape, data type, and the number of elements in the array. Inspect
#the shape of the temperatures_w1 array.

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Shape of the array:", temperatures_w1.shape)


Shape of the array: (7,)


In [ ]:
#Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
#Fahrenheit = (Celsius * 9/5) + 32
#Find the maximum, minimum, and mean temperatures for the week.

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

temperatures_f = (temperatures_w1 * 9/5) + 32

# Find maximum, minimum, and mean temperature
maximum_temp = np.max(temperatures_w1)
minimum_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Temperatures in Celsius:")
print(temperatures_w1)

print("\nTemperatures in Fahrenheit:")
print(temperatures_f)

print("\nMaximum Temperature:", maximum_temp, "°C")
print("Minimum Temperature:", minimum_temp, "°C")
print("Mean Temperature:", round(mean_temp, 2), "°C")

Temperatures in Celsius:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1 °C
Minimum Temperature: 20.8 °C
Mean Temperature: 23.54 °C


In [ ]:
#Array Slicing and Indexing:
#Extract the temperatures for the first three days of the week.

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
first_three_days = temperatures_w1[:3]

print("Temperatures for the first three days:")
print(first_three_days)

Temperatures for the first three days:
[22.5 25.3 20.8]


In [ ]:
#Extract the temperatures for the weekend (last two days).

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

weekend_temperatures = temperatures_w1[-2:]

print("Weekend temperatures:")
print(weekend_temperatures)

Weekend temperatures:
[24.8 21.9]


In [ ]:
#Extract the temperatures for the middle three days of the week.

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

middle_three_days = temperatures_w1[2:5]

print("Middle three days temperatures:")
print(middle_three_days)

Middle three days temperatures:
[20.8 23.4 26.1]


In [ ]:
#Create a 2D NumPy array named temperatures where each row represents
#temperatures for a different week:
#Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
#Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

import numpy as np
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print("Temperature data:")
print(temperatures)

Temperature data:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
#Inspect and print the shape, data type, and total number of elements in the
#temperatures array.

print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14


In [ ]:
#Extract the temperatures for each week and the weekends (last two days) for
#both weeks.

week1 = temperatures[0]
week2 = temperatures[1]

week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]

print("Week 1 temperatures:", week1)
print("Week 2 temperatures:", week2)

print("Week 1 weekend temperatures:", week1_weekend)
print("Week 2 weekend temperatures:", week2_weekend)

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend temperatures: [24.8 21.9]
Week 2 weekend temperatures: [22.8 20.1]


In [ ]:
# Create a Pandas Series named marks with the following data:
#Marks: 95, 92, 89, 85, 80
#Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'
import pandas as pd
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
#Use the integer index position to access the mark of the 1st rank student.

print("Mark of 1st rank student:", marks.iloc[0])

Mark of 1st rank student: 95


In [ ]:
#Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
#labels.
top_3 = marks.loc[['Rank1', 'Rank2', 'Rank3']]
print("Marks of top 3 ranks:")
print(top_3)


Marks of top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
#Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
third_rank_mark = marks.iloc[2]
print("Mark of 3rd-ranked student:", third_rank_mark)

Mark of 3rd-ranked student: 89


In [ ]:
#Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
#greater than 90.

mask = marks > 90
result = marks[mask]

print("Ranks with marks greater than 90:")
print(result)

Ranks with marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


In [ ]:
#Modify the mark of the student with the 1st rank to 100.
marks.loc['Rank1'] = 100

print("Updated marks:")
print(marks)

Updated marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
#Remove the entry corresponding to the last rank from the Series.
marks = marks.drop('Rank5')

print("Updated marks:")
print(marks)

Updated marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
#Compute the CGPA by dividing each mark in the Series by 10.
cgpa = marks / 10

print("CGPA:")
print(cgpa)

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
# Create a Pandas DataFrame named transactions with the following data: ➢
#TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
})

print(transactions)

   TransactionID
0            101
1            102
2            103
3            104
4            105
5            106
6            107
7            108
8            109
9            110


In [ ]:
#ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
#'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "ProductCategory": [
        "Electronics",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Furniture",
        "Electronics"
    ]
})
print(transactions)

   TransactionID ProductCategory
0            101     Electronics
1            102        Clothing
2            103     Electronics
3            104       Furniture
4            105        Clothing
5            106     Electronics
6            107       Furniture
7            108        Clothing
8            109       Furniture
9            110     Electronics


In [ ]:
#Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
#'North'
transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],

    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ]
})

print(transactions)

   TransactionID ProductCategory Region
0            101     Electronics  North
1            102        Clothing  South
2            103     Electronics  North
3            104       Furniture   East
4            105        Clothing   West
5            106     Electronics  North
6            107       Furniture   East
7            108        Clothing   West
8            109       Furniture  South
9            110     Electronics  North


In [ ]:
#Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400
transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],

    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],

    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
#Display the transactions DataFrame and its basic information, including head, tail,
#shape, column names, and data types.

print("Transactions DataFrame:")
print(transactions)

# Display the first 5 rows
print("\nFirst 5 rows:")
print(transactions.head())

# Display the last 5 rows
print("\nLast 5 rows:")
print(transactions.tail())

# Display the shape
print("\nShape:")
print(transactions.shape)

# Display column names
print("\nColumn names:")
print(transactions.columns)

# Display data types
print("\nData types:")
print(transactions.dtypes)


Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

First 5 rows:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   

In [ ]:
#Display only the 'ProductCategory' and 'Amount' columns.
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
#Retrieve the last 3 columns of the DataFrame using iloc or loc.
last_three_columns = transactions.iloc[:, -3:]
print(last_three_columns)

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_data)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
#Find the value counts for the 'ProductCategory' column.

category_counts = transactions['ProductCategory'].value_counts()
print(category_counts)

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
#Find the unique values in the 'Region' column.
unique_regions = transactions['Region'].unique()

print("Unique regions:")
print(unique_regions)

Unique regions:
['North' 'South' 'East' 'West']


In [ ]:
#Group by 'Region' and find the mean amount for each region.
region_mean = transactions.groupby('Region')['Amount'].mean()

print("Mean Amount for each Region:")
print(region_mean)

Mean Amount for each Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
#Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print(transactions[transactions['TransactionID'] == 102])

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165


In [ ]:
#Add a new column 'Discount' by calculating 10% of the 'Amount'.
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
#Remove the row with TransactionID 109.

transactions = transactions[transactions['TransactionID'] != 109]

print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


In [ ]:
#Delete the 'Discount' column from the DataFrame.
transactions = transactions.drop('Discount', axis=1)

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
